import { MainLayout } from '../components'
import { primaryFont } from '../fonts'
import { DataProvider } from '../context/DataProvider'
import {AuthProvider} from '@/context/AuthContext'
// toast messages
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { Zoom } from 'react-toastify';

import './globalStyles.scss'

export const metadata = {
  title: 'VeganVibe Cosmetsy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <AuthProvider>
          <DataProvider>
            <MainLayout>
              {children}
            </MainLayout>
          </DataProvider>
        </AuthProvider>
        <ToastContainer className={`toastify-custom-style`}
          hideProgressBar={false}
          autoClose={1000}
          position='bottom-right'
          transition={Zoom}
          pauseOnHover={true}
        />
      </body>
    </html>
  )
}
